name: Capybara_Rescue_App
options:
  bundleIdPrefix: com.capybara
  deploymentTarget:
    iOS: "17.0"
  developmentLanguage: en
  xcodeVersion: "15.0"

packages:
  GoogleMobileAds:
    url: https://github.com/googleads/swift-package-manager-google-mobile-ads.git
    from: 12.14.0
  GoogleUserMessagingPlatform:
    url: https://github.com/googleads/swift-package-manager-google-user-messaging-platform.git
    from: 3.1.0

targets:
  Capybara_Rescue_App:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    dependencies:
      - package: GoogleMobileAds
      - package: GoogleUserMessagingPlatform
    sources:
      - path: Capybara_Rescue_App
        excludes:
          - "*.md"
          - "*.png"
          - "*.usdz"
    resources:
      - path: Capybara_Rescue_App/Assets.xcassets
        type: assetCatalog
      - path: Capybara_Rescue_App/Capybara.usdz
      - path: Capybara_Rescue_App/Tophat.usdz
      - path: Capybara_Rescue_App/Santahat.usdz
      - path: Capybara_Rescue_App/Sombrero2hat.usdz
      - path: Capybara_Rescue_App/Sunflower.usdz
      - path: Capybara_Rescue_App/iconcapybara.png
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.capybara.rescue
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        SWIFT_VERSION: "5.0"
        TARGETED_DEVICE_FAMILY: "1,2"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: ""
        INFOPLIST_KEY_CFBundleDisplayName: "Capybara Rescue Universe"
        INFOPLIST_KEY_CFBundleShortVersionString: "1.0"
        INFOPLIST_KEY_CFBundleVersion: "1"
